version: 0.0.0.{build}
skip_tags: true
skip_branch_with_pr: true
environment:
  matrix:
  - PYTHON_VERSION: 3.4
    PYTHON: C:\Python34
    PYTHON_ARCH: x86
  - PYTHON_VERSION: 3.5
    PYTHON: C:\Python35
    PYTHON_ARCH: x86
  - PYTHON_VERSION: 3.6
    PYTHON: C:\Python36
    PYTHON_ARCH: x86
  - PYTHON_VERSION: 3.4
    PYTHON: C:\Python34-x64
    PYTHON_ARCH: x64
  - PYTHON_VERSION: 3.5
    PYTHON: C:\Python35-x64
    PYTHON_ARCH: x64
  - PYTHON_VERSION: 3.6
    PYTHON: C:\Python36-x64
    PYTHON_ARCH: x64
# disabled due to broken AppVeyor config - wrong pip resolved
  # - PYTHON_VERSION: Miniconda-3.4
  #   PYTHON: C:\Miniconda34
  #   PYTHON_ARCH: x86
  - PYTHON_VERSION: Miniconda-3.5
    PYTHON: C:\Miniconda35
    PYTHON_ARCH: x86
  - PYTHON_VERSION: Miniconda-3.6
    PYTHON: C:\Miniconda36
    PYTHON_ARCH: x86
# disabled due to broken AppVeyor config - wrong pip resolved
  # - PYTHON_VERSION: Miniconda-3.4
  #   PYTHON: C:\Miniconda34-x64
  #   PYTHON_ARCH: x64
  - PYTHON_VERSION: Miniconda-3.5
    PYTHON: C:\Miniconda35-x64
    PYTHON_ARCH: x64
  - PYTHON_VERSION: Miniconda-3.6
    PYTHON: C:\Miniconda36-x64
    PYTHON_ARCH: x64
install:
- cmd: >-
    SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    python --version

    pip --version

    pip install -r requirements.txt
build_script:
- cmd: python setup.py build
test_script:
- cmd: python -m unittest discover
artifacts:
- path: build/*
  name: python_packages
notifications:
# this publishes to Continuous Integration channel in Glip
- provider: Webhook
  url:
    secure: V16hjhyXfcLNyhNUih9v1Lb4wDly5r6CNNufciMrvllwt0m0rkguf6o4DY7pbdKia/vJGmErvQLdEW0MkzqsAhLWiPY7+Z6qvzFjweP8xNg=
  method: POST
  content_type: application/json
  body: >-
    {
      "icon": "https://www.appveyor.com/assets/img/appveyor-logo-256.png",
      "activity": "AppVeyor for spectre-divik",
      "title": "Build {{buildVersion}} **{{#failed}}failed{{/failed}}{{#passed}}passed{{/passed}}** in {{duration}}",
      "body": "{{#isPullRequest}}Pull request: [#{{pullRequestId}}](https://github.com/spectre-team/spectre-divik/pull/{{pullRequestId}})\n{{/isPullRequest}}Branch: [{{branch}}](https://github.com/spectre-team/spectre-divik/tree/{{branch}})\nCommit: [{{commitId}} {{commitMessage}}](https://github.com/spectre-team/spectre-divik/commit/{{commitId}})\nAuthor: {{commitAuthor}}\n[Build details]({{buildUrl}})"
    }
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
